#!/bin/bash

# local configuration for i3

# host specific setup
host=$(uname -n)
if [ "$host" == "hum" ]; then
	 # Apple Alum
	 # - caps is hyper
	 # - compose is right alt
	 setxkbmap -option 'caps:hyper' -option 'compose:ralt'
	 xrandr --output DVI-I-1 --left-of HDMI-1
	 xrandr --output DVI-I-1 --primary
	 dropbox start -i
elif [ "$host" == "jh-rvueb" ]; then
	# Realforce 87U
	# - caps is hyper
	# - swap alt/win so window keys next to spacebar
	# - and make compose key be the old windows key
	setxkbmap -option 'caps:hyper' -option 'altwin:swap_alt_win' -option 'compose:rwin'
	xrandr --output HDMI-0 --primary
else
	echo "Unknown host |$host|"
	setxkbmap -option 'caps:hyper' -option 'compose:ralt'
fi
xkb=${HOME}/.config/xkb
if [ -r "${xkb}" ]; then
	setxkbmap -print | sed -e '/xkb_symbols/s/"[[:space:]]/+local&/' | xkbcomp -I${xkb} - ${DISPLAY}
fi
xsettingsd -c ~/.config/xsettingsd &
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1  # gui authentication
