#!/bin/bash
#
# Download and install emacs

if [ $EUID -ne 0 ]; then
	echo "This script must be run with root privileges" 1>&2
	exit 1
fi
if [ $SUDO_USER ]; then
    real_user=$SUDO_USER
else
    real_user=$(whoami)
fi
USER="sudo -u $real_user"

version=28.2
tarfile=emacs.tar.xz
srcfile="https://ftp.gnu.org/gnu/emacs/emacs-${version}.tar.xz"

if [ ! -e $tarfile ]; then
    $USER curl -o $tarfile $srcfile
    if [ ! -e $tarfile ]; then
        echo "Failed to download $srcfile"
        exit -1
    fi
fi
if [ ! -e emacs-${version} ]; then
    $USER tar xf $tarfile
    if [ ! -d emacs-${version} ]; then
        echo "Failed to extract emacs"
        exit -1
    fi
fi
cd emacs-${version}
$USER ./configure --quiet --with-native-compilation --with-mailutils --with-imagemagick
$USER make --silent
make --silent install
cd ..
if type emacs > /dev/null 2>&1; then
    $USER rm -rf emacs-${version}
    $USER rm -f $tarfile
else
    echo "Problem making emacs, leaving emacs-${version}/ and $tarfile"
fi
