#!/bin/bash
#
# Make sure some system packages are present. These are only the
# most basic packages needed to set up a basic system, plus a few
# nice-to-haves.
#
# strict mode
set -euo pipefail

# in case we need it...
script_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

need_cmd() {
    command -v "$1" >/dev/null 2>&1 || {
        echo "Required command not found: $1" >&2
        exit 1
    }
}
# Preconditions
need_cmd gsettings



# turn off the exposé function
gsettings set org.gnome.mutter overlay-key ''
# right control is compose
# caps lock is super
# windows key is hyper
gsettings set org.gnome.desktop.input-sources xkb-options "['caps:super', 'altwin:hyper_win', 'compose:rctrl']"
