#!/bin/bash
#
# Make sure some local packages are present.

if [ $EUID -eq 0 ]; then
	echo "This script must NOT be run with root privileges" 1>&2
	exit 1
fi

if [ "$RUSTUP_HOME" == "" -o "$CARGO_HOME" == "" ]; then
	echo "Make sure RUSTUP_HOME and CARGO_HOME are defined"
	exit 1
fi

if [ ! -f ${RUSTUP_HOME}/settings.toml ]; then
	curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
else
	rustup update
fi

ln -fs ${PWD}/../cargo/config.toml ${CARGO_HOME}/config.toml

p="starship cargo-audit cargo-geiger cargo-outdated"
p="$p cargo-modules tokei sccache cargo-supply-chain"

for pkg in $p; do
	if type $pkg > /dev/null 2>&1; then
        echo "$pkg is already installed"
    else
        echo "Installing $pkg"
        cargo install --quiet $pkg
    fi
done

echo "Updating all packages"
cargo install-update --all

echo "Update completions"
mkdir -p ${XDG_DATA_HOME}/bash-completion/completions
rustup completions bash > ${XDG_DATA_HOME}/bash-completion/completions/rustup
ln -fs $(rustc --print sysroot)/etc/bash_completion.d/cargo  ${XDG_DATA_HOME}/bash-completion/completions/cargo

echo "Get rust-analyzer from https://github.com/rust-lang/rust-analyzer/releases"
