#!/bin/bash

# Update any repositories needed for most recent versions of some packages

if [[ $EUID -ne 0 ]]; then
	echo "This script must be run with root privilegs" 1>&2
	exit 1
fi

# Mint or Ubuntu
add-apt-repository --yes ppa:pithos/ppa
echo "deb http://debian.sur5r.net/i3/ $(lsb_release -u -c -s) universe" >> /etc/apt/sources.list
apt-get --allow-unauthenticated install sur5r-keyring

# Ubuntu-only repos
if hash lsb_release 2> /dev/null; then
	if [[ "$(lsb_release -ds)" =~ "Ubuntu" ]]; then
		add-apt-repository --yes ppa:webupd8team/nemo
	fi
fi

apt-get update

