#!/bin/bash
#
# Make sure some system packages are present. These are only the
# most basic packages needed to set up a basic system, plus a few
# nice-to-haves.

if [[ $EUID -ne 0 ]]; then
	echo "This script must be run with root privileges" 1>&2
	exit 1
fi

p=""
if [ "${OSTYPE:0:10}" == 'linux-gnue' ]; then
  p="$p ack-grep autojump htop screen"
  apt-get --quiet --yes --no-install-recommends install $p
elif [ "${OSTYPE:0:5}" == 'linux' ]; then
  apt-get --quiet --yes purge mono-runtime
  p="$p ttf-mscorefonts-installer otf-stix unifont ttf-ancient-fonts"
  p="$p python3-pip gparted"
  p="$p ack-grep silversearcher-ag autojump htop screen unzip"
  p="$p curl wget suckless-tools tree xclip"
  p="$p git-core gitk git-doc git-gui"
  p="$p vim-gnome exuberant-ctags rxvt-unicode-256color"
  p="$p python3 python3-gi python3-dev python3-pip python-pip"
  p="$p clipit pithos i3 i3lock i3status qalculate gsimplecal"
  p="$p nemo nemo-fileroller nemo-dropbox a2ps"
  p="$p libiw-dev chromium-browser"
  apt-get --quiet --yes install $p
elif [ "${OSTYPE:0:6}" == 'darwin' ]; then
  port selfupdate
  p="$p wget unison ctags"
  p="$p highlight p5-app-ack grep +nls"
# lesspipe
  port install -p $p
fi

# install some python stuff
# for now assume pip on all platforms
pip3 install --upgrade py3status netifaces colour psutil basiciw i3-py pygments
pip install --upgrade pygments
