#!/bin/bash
#
# Make sure some system packages are present. These are only the
# most basic packages needed to set up a basic system, plus a few
# nice-to-haves.

if [ $EUID -ne 0 ]; then
	echo "This script must be run with root privileges" 1>&2
	exit 1
fi
script_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

p=""
if [ "${OSTYPE:0:10}" == 'linux-gnue' ]; then
	p="$p ack-grep autojump htop screen"
	apt-get --quiet --yes --no-install-recommends install $p
elif [ "${OSTYPE:0:5}" == 'linux' ]; then

	. ${script_path}/../bin/common/linux.sh
	linux=$(linux_distribution_name)
	version=$(linux_distribution_version)

 # fonts
	p="$p ttf-mscorefonts-installer otf-stix unifont"
 # cli tools
	p="$p git-core gitk git-doc git-gui"
	p="$p ack-grep silversearcher-ag autojump htop screen unzip"
	p="$p curl wget suckless-tools tree xclip realpath a2ps"
 # python
	p="$p python3 python3-gi python3-dev python3-setuptools"
	p="$p python-dev python-pip"
 # desktop related
	p="$p i3 i3-wm i3lock i3status xsettingsd udevil"
	p="$p gsimplecal clipit gnome-alsamixer scrot xautolock"
 # nice to have apps & related
	p="$p pithos"
	p="$p qalculate"
	p="$p gparted nemo nemo-fileroller"
	p="$p vim-gnome rxvt-unicode-256color"
 # support for python stuff below
	p="$p libiw-dev"

 # version variations
	if [ "$linux" == "Ubuntu" ]; then
		if [ $version -ge 1510 ]; then
			p="$p ttf-ancient-fonts-symbola"
			# no nemo-dropbox yet...
		elif [ $version -lt 1510 ]; then
			p="$p ttf-ancient-fonts"
			p="$p nemo-dropbox"
		fi
	fi
	apt-get --ignore-missing --quiet --yes install $p
	easy_install3 pip
	pip3 install --upgrade py3status netifaces colour psutil basiciw i3-py pygments
	pip install --upgrade pygments
elif [ "${OSTYPE:0:6}" == 'darwin' ]; then
	brew update
	p="$p coreutils git autojump the_silver_searcher lesspipe tree"
	brew install $p
fi
