#!/bin/bash
# 
# Make sure some system packages are present
# 
# Includes some common software development packages, other 
# projects should have their own script as needed

p=""
if [ "${OSTYPE:0:10}" == 'linux-gnue' ]; then
  p="$p build-essential ccache"
  p="$p libboost-all-dev"
  p="$p autoconf automake libtool"
  p="$p python-dev python-setuptools python-serial python-daemon"
  p="$p python3-dev python3-setuptools python3-serial"
  apt-get --quiet --yes --no-install-recommends install $p
elif [ "${OSTYPE:0:5}" == 'linux' ]; then 
  p="$p rdoc ri"
  p="$p scons cmake-gui build-essential ccache" 
  p="$p manpages-dev manpages-posix-dev doxygen"
  p="$p gcc-doc glibc-doc"
  p="$p gcc-multilib libgmp-dev libmpc-dev libmpfr-dev ppl-dev libcloog-ppl-dev"         # gcc cross compiler support
  p="$p autoconf automake libtool gettext intltool"
  p="$p libboost-all-dev libboost-dbg libboost-doc libgtest-dev"
  p="$p qt-sdk"
  p="$p sqlite3 libsqlite3-dev sqlite3-doc"
  p="$p python3-dev python3-serial"
  p="$p python-setuptools python3-setuptools"
  apt-get --quiet --yes --no-install-recommends install $p
elif [ "${OSTYPE:0:6}" == 'darwin' ]; then 
  port selfupdate
  p="$p coreutils git-core +bash_completion"
  p="$p wget unison ctags"
  p="$p texlive-latex texlive-latex-recommended texlive-latex-extra p5-text-multimarkdown"
  p="$p highlight p5-app-ack grep +nls"
# lesspipe
  port install -p $p 
fi
