#!/bin/bash

# Update any repositories needed for most recent versions of some packages

if [[ $EUID -ne 0 ]]; then
	echo "This script must be run with root privilegs" 1>&2
	exit 1
fi

# need lsb_release functionality...
if hash lsb_release 2> /dev/null; then

	release=$(lsb_release -ds)
	echo $release

	# Ubuntu 14.04 LTS
	if [[ "$release" =~ "Ubuntu 14.04" ]]; then
		# pithos
		add-apt-repository --yes ppa:pithos/ppa
		add-apt-repository --yes ppa:lvillani/silversearcher
	fi

	# Any Ubuntu
	if [[ "$release" =~ "Ubuntu" ]]; then
		# git
		if [ "$(find /etc/apt/sources.list.d/ -name git-core-*.list)" != "" ]; then
			echo "Skipping git ppa setup, seems to be preset"
		else
			add-apt-repository --yes ppa:git-core/ppa
		fi
		# i3
		if [ -r ~/.cache/i3/keyring.deb ]; then
			echo "Skipping i3 ppa setup, seems we already did it"
		else
			mkdir -p ~/.cache/i3
			/usr/lib/apt/apt-helper download-file https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2020.02.03_all.deb ~/.cache/i3/keyring.deb SHA256:c5dd35231930e3c8d6a9d9539c846023fe1a08e4b073ef0d2833acd815d80d48
			dpkg -i ~/.cache/i3/keyring.deb
			echo "deb https://debian.sur5r.net/i3/ $(grep '^DISTRIB_CODENAME=' /etc/lsb-release | cut -f2 -d=) universe" >> /etc/apt/sources.list.d/sur5r-i3.list
		fi
		# emacs
		if [ "$(find /etc/apt/sources.list.d/ -name kelleyk-*.list)" != "" ]; then
			echo "Skipping emacs ppa setup, seems to be preset"
		else
			add-apt-repository --yes ppa:kelleyk/emacs
		fi
		# python

		if [ "$(find /etc/apt/sources.list.d/ -name deadsnakes-*.list)" != "" ]; then
			echo "Skipping python ppa setup, already present"
		else
			add-apt-repository --yes ppa:deadsnakes/ppa
		fi
	fi
	apt-get update
fi

