#!/bin/bash

# Update any repositories needed for most recent versions of some packages

if [[ $EUID -ne 0 ]]; then
	echo "This script must be run with root privilegs" 1>&2
	exit 1
fi

# need lsb_release functionality...
if hash lsb_release 2> /dev/null; then

	release=$(lsb_release -ds)
	echo $release

	# Ubuntu 14.04 LTS
	if [[ "$release" =~ "Ubuntu 14.04" ]]; then
		# pithos
		add-apt-repository --yes ppa:pithos/ppa
		add-apt-repository --yes ppa:lvillani/silversearcher
	fi

	# Any Ubuntu
	if [[ "$release" =~ "Ubuntu" ]]; then
		# git
		add-apt-repository --yes ppa:git-core/ppa
		# nemo
		add-apt-repository --yes ppa:webupd8team/nemo
		# i3
		echo "deb http://debian.sur5r.net/i3/ $(lsb_release -c -s) universe" >> /etc/apt/sources.list
	fi
	apt-get update
	apt-get --allow-unauthenticated install sur5r-keyring
fi


