#!/bin/bash
#
# Make sure some development packages are present
#
# Includes some common software development packages, other
# projects should have their own script as needed
if [[ $EUID -ne 0 ]]; then
	echo "This script must be run with root privilegs" 1>&2
	exit 1
fi

p=""
if [ "${OSTYPE:0:10}" == 'linux-gnue' ]; then
	p="$p build-essential ccache"
	p="$p libboost-all-dev"
	p="$p autoconf automake libtool"
	p="$p python3-dev "
	apt-get --quiet --yes --no-install-recommends install $p
elif [ "${OSTYPE:0:5}" == 'linux' ]; then
	p="$p rdoc ri doxygen"
	p="$p cmake-gui build-essential ccache"
	p="$p manpages-dev manpages-posix-dev ncurses-doc"
	p="$p gcc-doc glibc-doc"
	p="$p gcc-multilib libgmp-dev libmpc-dev libmpfr-dev ppl-dev libcloog-ppl-dev"         # gcc cross compiler support
	p="$p libzmq-dev "                                                           # python pkg support
	p="$p autoconf automake libtool gettext intltool"
	p="$p clang"
	p="$p meld git-gui mercurial subversion "
	apt-get --quiet --yes install $p
	pip3 install --upgrade pyserial ipython[notebook] pyzmq jinja2 tornado jsonschema matplotlib
	echo "NOTE: Install global via source, debian is out of date"
elif [ "${OSTYPE:0:6}" == 'darwin' ]; then
	brew update
	p="$p global --with-pygments "
	p="$p cmake "
	p="$p macvim emacs --with-cocoa"
	brew install $p
fi
