#!/bin/bash
#
# Packages needed for special development purposes
#
if [[ $EUID -ne 0 ]]; then
	echo "This script must be run with root privilegs" 1>&2
	exit 1
fi

p=""
if [ "${OSTYPE:0:10}" == 'linux-gnue' ]; then
	apt-get --quiet --yes --no-install-recommends install $p
elif [ "${OSTYPE:0:5}" == 'linux' ]; then
  # i3 building
	p="$p libzmq3-dev libpng-dev libfreetype6-dev"
	p="$p libxcb1-dev libxcb-util0-dev libxkbcommon-dev libxkbcommon-x11-dev libxcb-keysyms1-dev libxcb-cursor-dev"
	p="$p libxcb-randr0-dev libxcb-icccm4-dev libxcb-xinerama0-dev"
	p="$p libev-dev libyajl-dev libpcre3-dev libstartup-notification0-dev libpango1.0-dev libcairo-dev"
  # rust work
	p="$p libxcb-shape0-dev libxcb-xfixes0-dev libxcb-render0-dev"
	p="$p libssl-dev libspeechd-dev"
	apt-get --quiet --ignore-missing --yes install $p

  # python notebook
	pip3 install --upgrade pyserial ipython[notebook] pyzmq jinja2 tornado jsonschema matplotlib
elif [ "${OSTYPE:0:6}" == 'darwin' ]; then
	brew update
	brew install $p
fi
