#!/bin/bash
#
# Make sure some system packages are present. These are only the
# most basic packages needed to set up a basic system, plus a few
# nice-to-haves.
#
# Currently requires the following to already be installed:
# pip, pip3, curl

if [ $EUID -ne 0 ]; then
	echo "This script must be run with root privileges" 1>&2
	exit 1
fi
# strict mode
set -euo pipefail

# prepend $USER to reduce privileges
if [ $SUDO_USER ]; then
    real_user=$SUDO_USER
else
    real_user=$(whoami)
fi
USER="sudo -u $real_user"

pp="colour psutil basiciw"
$USER pip3 install --upgrade $pp

# need this where i3 can find them, so install as root
pr="py3status i3-py"
pip3 install --upgrade $pr

rg="asciidoctor asciidoctor-diagram asciidoctor-pdf"
rg="$rg rouge"
$USER gem install --user-install --conservative $rg

# a2s for fixing ascii-art diagrams
#$USER go install github.com/asciitosvg/cmd/a2s@latest
