#!/bin/bash
#
# Make sure some system packages are present. These are only the
# most basic packages needed to set up a basic system, plus a few
# nice-to-haves.
#
# Currently requires the following to already be installed:
# pip, pip3, curl

if [ $EUID -ne 0 ]; then
	echo "This script must be run with root privileges" 1>&2
	exit 1
fi
script_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

p=""
if [ "${OSTYPE:0:10}" == 'linux-gnue' ]; then
	p="$p ack-grep autojump htop screen"
	apt-get --quiet --yes --no-install-recommends install $p
elif [ "${OSTYPE:0:5}" == 'linux' ]; then

	. ${script_path}/../bin/common/linux.sh
	linux=$(linux_distribution_name)
	version=$(linux_distribution_version)
 if [ "$linux" == 'Ubuntu' ]; then

 # fonts
	p="$p ttf-mscorefonts-installer otf-stix unifont fonts-noto"
 # cli tools
	p="$p git-core gitk git-doc git-gui gpp"
	p="$p ack-grep silversearcher-ag autojump htop screen unzip"
	p="$p curl wget suckless-tools tree dstat xclip a2ps"
 # python
	p="$p python3 python3-gi python3-dev python3-setuptools"
	p="$p python-dev python-pip"
 # desktop related
	p="$p i3 i3-wm i3lock i3status xsettingsd udiskie wmctrl"
	p="$p clipit pavucontrol scrot xautolock"
	p="$p qalculate gnome-calendar"
 # nice to have apps & related
	p="$p pithos"
	p="$p gparted"
	p="$p vim-gnome rxvt-unicode-256color"
	p="$p hunspell"
 # support for python stuff below
	p="$p libiw-dev"

 # version variations
	if [ $version -ge 1510 ]; then
		p="$p ttf-ancient-fonts-symbola"
		p="$p fonts-fantasque-sans"
		if [ $version -ge 1604 ]; then
			p="$p fonts-hack-otf"
		fi
	elif [ $version -lt 1510 ]; then
		p="$p ttf-ancient-fonts"
	fi
	if [ $version -ge 1804 ]; then
		p="$p"
	else
		p="$p realpath"
	fi
	if [ $version -ge 1810 ]; then
	  p="$p ripgrep"
	else
		if [ "$(which rg)" == ""  ]; then
			curl -L -o ripgrep.deb https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep_11.0.2_amd64.deb
			dpkg -i ripgrep.deb
			rm -f ripgrep.deb
		fi
	fi
	apt-get --ignore-missing --quiet --yes install $p
	#easy_install3 pip
	pip3 install --upgrade py3status netifaces colour psutil basiciw i3-py pygments
	pip install --upgrade pygments

 elif [ "$linux" == 'Fedora' ]; then
 # version is currently 28

 # fonts
	p="$p mscore-fonts stix-fonts unifont-fonts google-noto-sans-fonts"
 
 # cli tools
	p="$p autojump ripgrep general-purpose-preprocessor jq"

 # desktop related
	p="$p i3 i3-ipc i3lock i3status dmenu udiskie wmctrl py3status scrot"
	p="$p rxvt-unicode-256color-ml scrot xautolock pavucontrol"

	dnf install -y $p
 fi

elif [ "${OSTYPE:0:6}" == 'darwin' ]; then
	brew update
	p="$p coreutils git autojump the_silver_searcher lesspipe tree"
	brew install $p
fi
