#!/bin/bash
#
# Make sure some system packages are present. These are only the
# most basic packages needed to set up a basic system, plus a few
# nice-to-haves.
#
# Currently requires the following to already be installed:
# pip, pip3, curl

if [ $EUID -ne 0 ]; then
	echo "This script must be run with root privileges" 1>&2
	exit 1
fi
# strict mode
set -euo pipefail

script_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. ${script_path}/../bin/common/linux.sh
linux=$(linux_distribution_name)
version=$(linux_distribution_version)

# prepend $USER to reduce privileges
if [ $SUDO_USER ]; then
    real_user=$SUDO_USER
else
    real_user=$(whoami)
fi
USER="sudo -u $real_user"

pp="colour psutil "
if [ "$linux" == 'ubuntu' ]; then
	pp="$pp basiciw"
fi
$USER pip3 install --upgrade $pp

# need this where i3 can find them, so install as root
if [ "$linux" == 'ubuntu' ]; then
	pr="i3-py py3status"
	pip3 install --upgrade $pr
fi

rg="asciidoctor asciidoctor-diagram asciidoctor-pdf asciidoctor-mathematical"
rg="$rg rouge"
$USER gem install --user-install --conservative $rg

# a2s for fixing ascii-art diagrams
#$USER go install github.com/asciitosvg/cmd/a2s@latest
