#!/bin/bash
#
# Make sure some system packages are present. These are only the
# most basic packages needed to set up a basic system, plus a few
# nice-to-haves.
#
# strict mode
set -euo pipefail

# in case we need it...
script_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

need_cmd() {
    command -v "$1" >/dev/null 2>&1 || {
        echo "Required command not found: $1" >&2
        exit 1
    }
}
# Preconditions
need_cmd sudo
need_cmd dnf

# Pre-authenticate sudo once
sudo -v

# base packages
pkgs=(
    autoconf automake stow pkg-config
    autojump clangd ripgrep tree
    git gitk
    vim emacs
)

# extras for any desktop
pkgs+=(
	 dejavu-fonts-all
    foot alacritty
    pavucontrol udiskie brightnessctl playerctl
    qalculate-gtk gnome-calendar
)

# desktop, especially for sway
pkgs+=(
    wl-clipboard wlrctl wtype xdg-desktop-portal-wlr
    wayland-utils wlr-randr
    sway swaybg swayidle swaylock waybar
    grim slurp foot wofi
    pavucontrol udiskie brightnessctl playerctl clipman
    j4-dmenu-desktop
)


sudo dnf install "${pkgs[@]}"


