#!/bin/bash
#
# Make sure some local packages are present.

if [ $EUID -eq 0 ]; then
	echo "This script must NOT be run with root privileges" 1>&2
	exit 1
fi
script_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# a2s for fixing ascii-art diagrams
go install github.com/asciitosvg/cmd/a2s@latest
